# Site settings
title: Maoliang Blog
SEOTitle: 懋靓的博客 | Maoliang‘Blog
header-img: img/post-bg-desk.jpg
email: maoliangli@outlook.com
description: "Stay Hungry, Stay Foolish."
keyword: "maoliangli"
url: "http://limaolliang.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/limaolliang/limaolliang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Stay Hungry, Stay Foolish!"
sidebar-avatar: /img/avatar1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     bai-ma-fei-ma-96-98
github_username:    limaolliang
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# todo:加上disqus评论系统
# Disqus（https://disqus.com/）
# disqus_username: limaolliang

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 0bb2764b3fc0f2bbda2c                            #生成的clientID
  clientSecret: 12b353400869712267d3c7586764142699f7402d    #生成的clientSecret
  repo: limaolliang.github.io    #仓库名称
  owner: limaolliang    #github用户名
  admin: limaolliang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩
  id: 'window.location.pathname'


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 8f5f16c8a5fb96c3098ace635023daf3

# Google Analytics
ga_track_id: ''            # Format: UA-xxxxxx-xx
ga_domain: 'www.maoliangli.com'               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "鸣帅",
        href: "https://whulm.cn/"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]

theme: jekyll-theme-architect
